### ISSUE TITLE
Database Location

### ISSUE THREAD

**Issue by iev6** [iitmcvg/OCR-Handwritten-Text#1]
Can you please add a google drive (access based) link for the database on the repo? 

Upload it to your SMail account's Google Drive, so that only CVG will have access.

**Comment by rsnk96** [comment]
https://drive.google.com/a/smail.iitm.ac.in/file/d/0B5_QSpyNgs5JZlZNNEw5LU5wQmc/view?usp=sharing

I'd recommend using `unzip` on terminal for the unzipping all of the  ~1million images. The Unzipping software that comes with Ubuntu and Windows unzips with errors for some reason.
